# Generated by Django 3.2.4 on 2021-06-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Pilot',
        ),
    ]
